### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by prashantkamdar** [Jean-MarcHarvengt/MCUME#11]
I am unable to build because files inside the folder of picovga_t4 are missing (PICOVGA_T4_SOURCES).

```
CMake Error at CMakeLists.txt:329 (add_executable):
  Cannot find source file:

    picovga_t4/vga_layer.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
```

Many files are missing.

Please help.

**Comment by Jean-MarcHarvengt** [comment]
All files are there. Please clone properly, clear build directory.
copy dependencies (SDK) ask explain in readme.txt file.
go to build dir.
cmake ..
make

**Comment by Jean-MarcHarvengt** [comment]
It seems the MCUME_pico/CMakeLists.txt was not the correct one and was never updated by me since I changed the VGA library!
I uploaded, it is default configured for C64 emu now!

Sorry...

**Comment by przem360** [comment]
Great! Thanks!
BTW - awesome project :)

**Comment by prashantkamdar** [comment]
thank you, this finally worked now!

```add_executable(mcume
		# ${GFXENGINE_SOURCES}
		# ${PICO20_SOURCES}
		# ${PICO64_SOURCES}
		# ${PICO81_SOURCES}
		# ${PICO800_SOURCES}
		# ${PICO5200_SOURCES}
		# ${PICO8086_SOURCES}
		# ${PICOCOLEM_SOURCES}
		# ${PICOO2EM_SOURCES}
		# ${PICOVCS_SOURCES}
		# ${PICOSPECCY_SOURCES}
		${PICONOFRENDO_SOURCES}
		# ${PICOSND_SOURCES}
		# ${TESTIO_SOURCES}
		# ${TESTVGA_SOURCES}
		# ${TESTKEYMAX_SOURCES}
		# ${TESTPSRAM_SOURCES}
		# ${PICOVALIDATION_SOURCES}
		# ${PSRAM_SOURCES}
		# ${VGA_T4_SOURCES}
		# ${PICOVGA_T4_SOURCES}
		${TFT_T_SOURCES}
	)
```

I copied the uf2 to pico in after building nofrendo.
