### ISSUE TITLE
TeeComputer schematic query

### ISSUE THREAD

**Issue by gadyke** [Jean-MarcHarvengt/MCUME#17]
Hi there,

I really like the TeeComputer concept and I've been trying to fill in some of the gaps by working back from the source code in place, but I wonder if you'd mind confirming/clarifying a couple of points in the schematic you've put up?

- Can you confirm what O0, I0, I1 and I2 are broken out for?
- I don't see the wiring for an analogue stick included (though I've seen you using one in your protoboard demo) - of course there are d-pad inputs wired up so I wonder if you switched?
- I wanted to check but I assume you aren't running the ILI from the onboard 3v3 regulator?
- Are the multiple RET and SPC buttons there to represent physically larger keys in a normal keyboard?

I did look around to see if anyone's published a layout implementing the schematic so I could work backward through that and answer my own Qs but afraid I couldn't find anything - sorry if I've missed a resource!

Regards,

Greg

**Comment by Jean-MarcHarvengt** [comment]
I still have to update the schematic with latest PCB I have created. I hope to have the rev 3 ready in 2 weeks and I will publish it all. The 7x7 input/output matrix should be all linked to the teensy and offers 42 keys on the keyboard. It is a mistake on the old schematic I guess. Again I will publish the update soon.

Analog stick is only was supported for MCUME board, not on TEECOMPUTER. TEECOMPUTER has C54 like digital joystick or the keypad of the keyboard (or a USB joystick). there are 3 SPC keys for space but should all be connected to same lines.
ILI and ST displays are powered by the 3.3 regulator too. Only USB is powered by the USB 5V.

**Comment by gadyke** [comment]
Thanks Jean-Marc, I look forward to your revised design!

I didn't realise the onboard LDO was beefy enough to also fund the ILI, interesting.

Noted re. analog, my mistake.

G
