### ISSUE TITLE
Pico64 display from right to left instead of left to right

### ISSUE THREAD

**Issue by jfoxr** [Jean-MarcHarvengt/MCUME#19]
I tried several builds for the PIComputer but my display is flipped left to right. It is an ILI9341 display. Any ideas?

**Comment by jfoxr** [comment]
I had too many displays enabled. Disabling everything but the display of interest worked perfectly. This is a great project. Thank you.

**Comment by Jean-MarcHarvengt** [comment]
indeed, you have to select the correct display in the platform_config file
