### ISSUE TITLE
sound on teensy 4.1 (pcm5102)

### ISSUE THREAD

**Issue by lastclass74** [Jean-MarcHarvengt/MCUME#6]
hi .. i dont have sound with uae or any of your emulators .. i checked pin 7 (out1a) no data ?!? .. but have data on pin 20,21 (bclk1) and (lrclk1) 

hope you can help me ;) 
thx

**Comment by Jean-MarcHarvengt** [comment]
Not sure anymore. I assume you use the teensy41 version on a teensy41. There is an option has sound but it is on by default. May be something with the SDK. I will check this we

**Comment by lastclass74** [comment]
Sound great .. love the emulators.. i tested the pcm5102 on a raspberry and
works fine .. think this is a software error somewhere .. hope you can
check it .. thx for the help

tor. 2. dec. 2021 08.08 skrev Jean-MarcHarvengt ***@***.***>:

**Comment by lastclass74** [comment]
what sdk version did you use ?
thanks for a great project hope you continue it .. love to see a snes
emulator and/or a vic 20 emulator
claus ..


Den tor. 2. dec. 2021 kl. 09.45 skrev Claus A ***@***.***>:

**Comment by Jean-MarcHarvengt** [comment]
Hi,

I just tested again.
Downloaded latest Teensysuino SDK 1.55 (Mac version)
I recompiled the Teensyuae41 GIT version also latest GIT VGA library and it is ok, I still have sound.
I used this module (price is like 10 times more than 1 year ago !!!)
https://www.amazon.nl/PCM5102-Decoder-GY-PCM5102-Interface-PCM5102A/dp/B07VNB54N4/ref=asc_df_B07VNB54N4/?tag=nlshogostdde-21&linkCode=df0&hvadid=517441560399&hvpos=&hvnetw=g&hvrand=2166077023826773566&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=20054&hvtargid=pla-1406149819862&psc=1

VIN => 3.3
GND to GND
LCK to pin 20 (LRCLK1)
DIN  to pin 9(out1C)
BCK to pin 21 (BCLK1)
(Arduino SDK is 1.8.13 but I guess it is not the issue)

I know that I do not connect I2C to the PCM5102 module so I assume default initialization. Not sure if that could be the issue.
Is it connected differently on the raspberry pi ?

The VIC20 emu runs on the raspberry PICO MCUME. Still have to port it back to the teensy.
SNES is tricky. I had started but roms are big. Best I could  have was  Super Mario world running for 60 secs I think


Regards,

J-M

**Comment by lastclass74** [comment]
Hi J-M.

Thanks for checking .. are you sure its pin 9 (out1c) on the schematics on
github it say pin 7 (out1a)
i try pin 9 still no go ;( .. so i order the same pcm5102 as you have.. and
a new teensy v4.1 just to be sure ;)
can you share the teensyuae41.ino.hex you compiled .. just to test if the
sdk at my end is bad ? thx ..

the teensy64 works great to but usb keyboard dont work (works fine in
filemenu)
the atari emulator i cant compile .. comes up with a error : expected
unqualified-id before 'do'
doom works fine ;)

thanks for all the help
claus ...


Den tir. 7. dec. 2021 kl. 21.32 skrev Jean-MarcHarvengt <
***@***.***>:

**Comment by Jean-MarcHarvengt** [comment]
Hi,

You are right, this is GPIO 7 (OUT1A!!), it is the 9th pin if you count from the ground at USB connector.[](url
[MCUME5VGA.zip](https://github.com/Jean-MarcHarvengt/MCUME/files/7678457/MCUME5VGA.zip)
)

Here are the HEXs for UAE and CASTAWAY ST emulator

J-M

**Comment by lastclass74** [comment]
Thanks, I'll check it out.

ons. 8. dec. 2021 20.39 skrev Jean-MarcHarvengt ***@***.***>:

**Comment by lastclass74** [comment]
Hi j-m..
still no go .. i have order new teensy and pcm5102 .. just have to wait and
see then .. thanks for the help

just checked the c64 emulator.. but usb keyboard dont work on c64 emulator
.. works in filemenu .. is this normal ?

claus ..


Den tor. 9. dec. 2021 kl. 06.16 skrev Claus A ***@***.***>:

**Comment by lastclass74** [comment]
Hi j-m
got a new teensy v4.1 today now sound works 100% !! ;)
thanks for all the help
you can close this now

claus ...


Den fre. 10. dec. 2021 kl. 18.19 skrev Claus A ***@***.***>:
