### ISSUE TITLE
MCUME_pico / builds

### ISSUE THREAD

**Issue by Kayto** [Jean-MarcHarvengt/MCUME#7]
Hi. 
I note that precompiled builds are available for MCUME Pico. Suggest readme is amended to add a note to this.

Compilation for Pico RetroVGA fails as starting message below. 
CMakeLists.txt refers to numerous missing sources from picovga_t4 and missing subdirectory /render.

_CMake Error at CMakeLists.txt:329 (add_executable):
  Cannot find source file:
    picovga_t4/vga_layer.cpp_

**Comment by alex-taras** [comment]
Looks like when picovga was stripped down, the CMakeLists file was not cleaned up, just delete everything in the picovga_t4 section that you don't see in the local folder and it'll build.

**Comment by Jean-MarcHarvengt** [comment]
I was looking at you problem and indeed I started by cleaning the build directory and no problem.
That means you had some old build directory because I don't push it with the git

**Comment by Kayto** [comment]
Thank both for the comments and clarification.
BTW. Great work, thanks.
